//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oberflaeche_kaelber.Forms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PKleinMilch1 {
            get {
                return ((double)(this["PKleinMilch1"]));
            }
            set {
                this["PKleinMilch1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PKleinMilch2 {
            get {
                return ((double)(this["PKleinMilch2"]));
            }
            set {
                this["PKleinMilch2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PKleinMilch3 {
            get {
                return ((double)(this["PKleinMilch3"]));
            }
            set {
                this["PKleinMilch3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PKleinMilch4 {
            get {
                return ((double)(this["PKleinMilch4"]));
            }
            set {
                this["PKleinMilch4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PKleinMilch5 {
            get {
                return ((double)(this["PKleinMilch5"]));
            }
            set {
                this["PKleinMilch5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PKleinMilch6 {
            get {
                return ((double)(this["PKleinMilch6"]));
            }
            set {
                this["PKleinMilch6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PKleinMilch7 {
            get {
                return ((double)(this["PKleinMilch7"]));
            }
            set {
                this["PKleinMilch7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PKleinMilch8 {
            get {
                return ((double)(this["PKleinMilch8"]));
            }
            set {
                this["PKleinMilch8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PKleinMilch9 {
            get {
                return ((double)(this["PKleinMilch9"]));
            }
            set {
                this["PKleinMilch9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PKleinMilch10 {
            get {
                return ((double)(this["PKleinMilch10"]));
            }
            set {
                this["PKleinMilch10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PKleinMilch11 {
            get {
                return ((double)(this["PKleinMilch11"]));
            }
            set {
                this["PKleinMilch11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PKleinMilch12 {
            get {
                return ((double)(this["PKleinMilch12"]));
            }
            set {
                this["PKleinMilch12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PKleinMilch13 {
            get {
                return ((double)(this["PKleinMilch13"]));
            }
            set {
                this["PKleinMilch13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PKleinMilch14 {
            get {
                return ((double)(this["PKleinMilch14"]));
            }
            set {
                this["PKleinMilch14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PKleinMilch15 {
            get {
                return ((double)(this["PKleinMilch15"]));
            }
            set {
                this["PKleinMilch15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PKleinKaelberstarter {
            get {
                return ((double)(this["PKleinKaelberstarter"]));
            }
            set {
                this["PKleinKaelberstarter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PKleinHeu {
            get {
                return ((double)(this["PKleinHeu"]));
            }
            set {
                this["PKleinHeu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PKleinWasser {
            get {
                return ((double)(this["PKleinWasser"]));
            }
            set {
                this["PKleinWasser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PKleinSilofutter {
            get {
                return ((double)(this["PKleinSilofutter"]));
            }
            set {
                this["PKleinSilofutter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PMittelMilch1 {
            get {
                return ((double)(this["PMittelMilch1"]));
            }
            set {
                this["PMittelMilch1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PMittelMilch2 {
            get {
                return ((double)(this["PMittelMilch2"]));
            }
            set {
                this["PMittelMilch2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PMittelMilch3 {
            get {
                return ((double)(this["PMittelMilch3"]));
            }
            set {
                this["PMittelMilch3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PMittelMilch4 {
            get {
                return ((double)(this["PMittelMilch4"]));
            }
            set {
                this["PMittelMilch4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PMittelMilch5 {
            get {
                return ((double)(this["PMittelMilch5"]));
            }
            set {
                this["PMittelMilch5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PMittelMilch6 {
            get {
                return ((double)(this["PMittelMilch6"]));
            }
            set {
                this["PMittelMilch6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PMittelMilch7 {
            get {
                return ((double)(this["PMittelMilch7"]));
            }
            set {
                this["PMittelMilch7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PMittelMilch8 {
            get {
                return ((double)(this["PMittelMilch8"]));
            }
            set {
                this["PMittelMilch8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PMittelMilch9 {
            get {
                return ((double)(this["PMittelMilch9"]));
            }
            set {
                this["PMittelMilch9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PMittelMilch10 {
            get {
                return ((double)(this["PMittelMilch10"]));
            }
            set {
                this["PMittelMilch10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PMittelMilch11 {
            get {
                return ((double)(this["PMittelMilch11"]));
            }
            set {
                this["PMittelMilch11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PMittelMilch12 {
            get {
                return ((double)(this["PMittelMilch12"]));
            }
            set {
                this["PMittelMilch12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PMittelMilch13 {
            get {
                return ((double)(this["PMittelMilch13"]));
            }
            set {
                this["PMittelMilch13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PMittelMilch14 {
            get {
                return ((double)(this["PMittelMilch14"]));
            }
            set {
                this["PMittelMilch14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PMittelMilch15 {
            get {
                return ((double)(this["PMittelMilch15"]));
            }
            set {
                this["PMittelMilch15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public double PMittelKaelberstarter {
            get {
                return ((double)(this["PMittelKaelberstarter"]));
            }
            set {
                this["PMittelKaelberstarter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public double PMittelHeu {
            get {
                return ((double)(this["PMittelHeu"]));
            }
            set {
                this["PMittelHeu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double PMittelWasser {
            get {
                return ((double)(this["PMittelWasser"]));
            }
            set {
                this["PMittelWasser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double PMittelSilofutter {
            get {
                return ((double)(this["PMittelSilofutter"]));
            }
            set {
                this["PMittelSilofutter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PGrossMilch1 {
            get {
                return ((double)(this["PGrossMilch1"]));
            }
            set {
                this["PGrossMilch1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PGrossMilch2 {
            get {
                return ((double)(this["PGrossMilch2"]));
            }
            set {
                this["PGrossMilch2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PGrossMilch3 {
            get {
                return ((double)(this["PGrossMilch3"]));
            }
            set {
                this["PGrossMilch3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PGrossMilch4 {
            get {
                return ((double)(this["PGrossMilch4"]));
            }
            set {
                this["PGrossMilch4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PGrossMilch5 {
            get {
                return ((double)(this["PGrossMilch5"]));
            }
            set {
                this["PGrossMilch5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PGrossMilch6 {
            get {
                return ((double)(this["PGrossMilch6"]));
            }
            set {
                this["PGrossMilch6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PGrossMilch7 {
            get {
                return ((double)(this["PGrossMilch7"]));
            }
            set {
                this["PGrossMilch7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PGrossMilch8 {
            get {
                return ((double)(this["PGrossMilch8"]));
            }
            set {
                this["PGrossMilch8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PGrossMilch9 {
            get {
                return ((double)(this["PGrossMilch9"]));
            }
            set {
                this["PGrossMilch9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PGrossMilch10 {
            get {
                return ((double)(this["PGrossMilch10"]));
            }
            set {
                this["PGrossMilch10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PGrossMilch11 {
            get {
                return ((double)(this["PGrossMilch11"]));
            }
            set {
                this["PGrossMilch11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PGrossMilch12 {
            get {
                return ((double)(this["PGrossMilch12"]));
            }
            set {
                this["PGrossMilch12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PGrossMilch13 {
            get {
                return ((double)(this["PGrossMilch13"]));
            }
            set {
                this["PGrossMilch13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PGrossMilch14 {
            get {
                return ((double)(this["PGrossMilch14"]));
            }
            set {
                this["PGrossMilch14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PGrossMilch15 {
            get {
                return ((double)(this["PGrossMilch15"]));
            }
            set {
                this["PGrossMilch15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public double PGrossKaelberstarter {
            get {
                return ((double)(this["PGrossKaelberstarter"]));
            }
            set {
                this["PGrossKaelberstarter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public double PGrossHeu {
            get {
                return ((double)(this["PGrossHeu"]));
            }
            set {
                this["PGrossHeu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double PGrossWasser {
            get {
                return ((double)(this["PGrossWasser"]));
            }
            set {
                this["PGrossWasser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double PGrossSilofutter {
            get {
                return ((double)(this["PGrossSilofutter"]));
            }
            set {
                this["PGrossSilofutter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double PMilchmast1 {
            get {
                return ((double)(this["PMilchmast1"]));
            }
            set {
                this["PMilchmast1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double PMilchmast2 {
            get {
                return ((double)(this["PMilchmast2"]));
            }
            set {
                this["PMilchmast2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double PMilchmast3 {
            get {
                return ((double)(this["PMilchmast3"]));
            }
            set {
                this["PMilchmast3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double PMilchmast4 {
            get {
                return ((double)(this["PMilchmast4"]));
            }
            set {
                this["PMilchmast4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double PMilchmast5 {
            get {
                return ((double)(this["PMilchmast5"]));
            }
            set {
                this["PMilchmast5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double PMilchmast6 {
            get {
                return ((double)(this["PMilchmast6"]));
            }
            set {
                this["PMilchmast6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public double PMilchmast7 {
            get {
                return ((double)(this["PMilchmast7"]));
            }
            set {
                this["PMilchmast7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public double PMilchmast8 {
            get {
                return ((double)(this["PMilchmast8"]));
            }
            set {
                this["PMilchmast8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public double PMilchmast9 {
            get {
                return ((double)(this["PMilchmast9"]));
            }
            set {
                this["PMilchmast9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double PMilchmast10 {
            get {
                return ((double)(this["PMilchmast10"]));
            }
            set {
                this["PMilchmast10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double PMilchmast11 {
            get {
                return ((double)(this["PMilchmast11"]));
            }
            set {
                this["PMilchmast11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double PMilchmast12 {
            get {
                return ((double)(this["PMilchmast12"]));
            }
            set {
                this["PMilchmast12"] = value;
            }
        }
    }
}
